on:
  push:
    branches:
      main
name: Publish Production Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.byethost12.com:21/swiftturtlelabs.byethost12.com/htdocs/AdventCalendar
        ftp-username: b12_14570845
        ftp-password: ${{ secrets.FTP_PASSWORD }}
